theme: jekyll-theme-leap-day
title: BiT21 OpenSource Projects
description: BiT21 is a software company passioned on helping people change their lives making smart use of technology. Software is magic, and developers are the magicians.

show_downloads: true
